### ISSUE TITLE
API 2.0

### ISSUE THREAD

**Issue by ai** [radeno/nanoid.rb#3]
Let’s update the library to be compatible with the latest Nano ID 2.0:

- [x] Replace `~` to `-` in default alphabet
- [x] Add `non-secure` fast generator

**Comment by radeno** [comment]
Hi @ai i will. So its the time to publish version 1.0 first as stable before changing.
Thanks for info.

**Comment by radeno** [comment]
On the way. Committed changes. Lets publish it.
